# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget Franka::franka Franka::libfranka-common)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target Franka::franka
add_library(Franka::franka SHARED IMPORTED)

set_target_properties(Franka::franka PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_attribute_deprecated;cxx_constexpr;cxx_defaulted_functions;cxx_deleted_functions;cxx_generalized_initializers;cxx_noexcept;cxx_uniform_initialization"
  INTERFACE_INCLUDE_DIRECTORIES "/home/prime/KISTAR_Hand_RTOS-master/Franka_Dual_Arm_PtoP/R_Franka_KISTAR_Hand/libfranka/include"
  INTERFACE_LINK_LIBRARIES "Franka::libfranka-common"
)

# Create imported target Franka::libfranka-common
add_library(Franka::libfranka-common INTERFACE IMPORTED)

set_target_properties(Franka::libfranka-common PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/prime/KISTAR_Hand_RTOS-master/Franka_Dual_Arm_PtoP/R_Franka_KISTAR_Hand/libfranka/common/include"
)

# Import target "Franka::franka" for configuration ""
set_property(TARGET Franka::franka APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(Franka::franka PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_NOCONFIG "Poco::Foundation;Poco::Net"
  IMPORTED_LOCATION_NOCONFIG "/home/prime/KISTAR_Hand_RTOS-master/Franka_Dual_Arm_PtoP/R_Franka_KISTAR_Hand/build/libfranka.so"
  IMPORTED_SONAME_NOCONFIG "libfranka.so"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
